### ISSUE TITLE
Hello World Example Not Working

### ISSUE THREAD

**Issue by arunksoman** [conductor-sdk/conductor-python#271]
While runing python conductor I am getting following error. EOFError: Ran out of input: 

The detailed stacktrace is given below:

```(venv) F:\differentbyte\conductor_test>python helloworld.py
2024-10-03 22:01:21,229 [13468] conductor.client.automator.task_handler INFO     created worker with name=greet and domain=None
2024-10-03 22:01:21,229 [13468] conductor.client.automator.task_handler INFO     TaskHandler initialized
2024-10-03 22:01:21,229 [13468] conductor.client.automator.task_handler INFO     Starting worker processes...
Traceback (most recent call last):
  File "F:\differentbyte\conductor_test\helloworld.py", line 39, in <module>
    main()
  File "F:\differentbyte\conductor_test\helloworld.py", line 24, in main
    task_handler.start_processes()
  File "F:\differentbyte\conductor_test\venv\Lib\site-packages\conductor\client\automator\task_handler.py", line 104, in start_processes
    self.__start_task_runner_processes()
  File "F:\differentbyte\conductor_test\venv\Lib\site-packages\conductor\client\automator\task_handler.py", line 158, in __start_task_runner_processes 
    task_runner_process.start()
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function greet at 0x00000191B8CC9580>: it's not the same object as greetings_worker.greet
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
```
How to resolve above error?

**Comment by jgard** [comment]
FYI, dupe of https://github.com/conductor-sdk/conductor-python/issues/264

**Comment by Netanel-ImagenAI** [comment]
I got the same error. I'm using a windows machine, so I tried using a linux docker container instead, and it worked.

**Comment by IgorChvyrov-sm** [comment]
Hi @arunksoman 

Thanks for reporting this issue! This appears to be the same pickling error that was discussed in [another thread](https://github.com/conductor-oss/python-sdk/issues/264). The solution has been provided there - please check out [this comment](https://github.com/conductor-oss/python-sdk/issues/264#issuecomment-3082590234) for a working workaround.

Let me know if you try the solution and still encounter problems - I'd be happy to help troubleshoot further!
